BOARD_TAG := atmega328_bb
BOARDS_TXT := $(realpath ../../boards/atmega328_bb.txt)
ARDUINO_LIBS := LiquidCrystal-1.0.7

ISP_PROG := stk500v1
ISP_PORT := /dev/ttyUART0

include $(realpath ../../Common.mk)
